# nome da Aplicação
spring.application.name=poupa-api

# configuração da conexão JDBC
spring.datasource.url=jdbc:postgresql://localhost:5432/poupa_db
spring.datasource.username=postgres
spring.datasource.password=02131621
